export const supplierForm = {
    first_name: { value: "", type: "text", columns: "col-6", validation: { length: 40, width: 6 }},
    last_name: { value: "", type: "text", columns: "col-6", validation: { length: 40, width: 6 }},
    job_title: { value: "", type: "text", columns: "col-6", validation: { length: 40, width: 6 }},
    company_name: { value: "", type: "text", columns: "col-6", validation: { length: 40, width: 6 }},
    address: { value: "", type: "text", columns: "col-6", validation: { length: 240, width: 6 }},
    state_or_province: { value: "", columns: "col-6", type: "text", validation: { length: 40, width: 6 }},
    city: { value: "", type: "text", columns: "col-6", validation: { length: 100, width: 6 }},
    postal_code: { value: "", type: "text", validation: { length: 5, width: 6 }},
    country: { value: "", type: "text", validation: { length: 100, width: 6 }},
    mobile_number: { value: "", type: "text", validation: { length: 10, width: 6 }},
    office_number: { value: "", type: "text", validation: { length: 10, width: 6 }},
    email: { value: "", type: "email", validation: { type: "email", length: 100, width: 6 }},
    classification: { value: "", type: "text", validation: { length: 20, width: 6 }},
    year_founded: { value: "", type: "text", validation: { length: 4, width: 6 }},
    website: { value: "", type: "text", validation: { length: 100, width: 6 }},
    quality_certifications: { value: "", type: "text", validation: { length: 20, width: 6 }},
    number_of_locations: { value: "", type: "text", validation: { type: "number", length: 4, width: 6 }},
    employee_size: { value: "", type: "text", validation: { type: "number", length: 6, width: 6 }},
    annual_sales: { value: "", type: "text", validation: { type: "number", length: 11, width: 6 }},
}