import { IForm, inputTypes, Columns, Variant, IInput } from "./FormInterfaces";
import { IOrganization } from "../Models/Organizations";

export const organizationSignupForm: IForm  = {
    formName: "organizationSignupForm",
    inputs: [
        {
            name: "name",
            label: false,
            displayName: "Company Name",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: true,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "street",
            label: false,
            displayName: "Street Number",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: true,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "state_province",
            label: false,
            displayName: "State or Province",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: true,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "city",
            label: false,
            displayName: "City",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: true,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "postalCode",
            label: false,
            displayName: "Postal Code",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string number",
                valid: null,
                required: true,
                lengthRequired: true,
                length: {min: 5, max: 10},
                validationMessage: "",
            }
        },
        {
            name: "country",
            label: false,
            displayName:"Country",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: true,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "phoneNumber",
            label: false,
            displayName:"Phone Number",
            value: "",
            type: inputTypes.tel,
            pattern: "[0-9]*",
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string number",
                valid: null,
                required: true,
                lengthRequired: true,
                length: {min: 10, max: 10},
                validationMessage: "",
            }
        },
        {
            name: "classification",
            label: false,
            displayName:"Classification",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: false,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "yearFounded",
            label: false,
            displayName:"Year Founded",
            value: "",
            type: inputTypes.number,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "number",
                valid: null,
                required: true,
                lengthRequired: true,
                length: {min: 4, max: 4},
                validationMessage: "",
            }
        },
        {
            name: "website",
            label: false,
            displayName:"Website",
            value: "",
            type: inputTypes.text,
            columns:Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                lengthRequired: false,
                required: false,
                validationMessage: "",
            }
        },
        {
            name: "qualityCertifications",
            label: false,
            displayName:"Quality Certifications",
            value: "",
            type: inputTypes.text,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: "string",
                valid: null,
                required: false,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "numberOfLocations",
            label: false,
            displayName:"Number Of Locations",
            value: "",
            type: inputTypes.number,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: inputTypes.number,
                valid: null,
                required: true,
                lengthRequired: true,
                length: {min: 1, max: 3},
                validationMessage: "",
            }
        },
        {
            name: "numberOfEmployees",
            label: false,
            displayName:"Employee Size",
            value: "",
            type: inputTypes.number,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: inputTypes.number,
                valid: null,
                required: true,
                lengthRequired: false,
                validationMessage: "",
            }
        },
        {
            name: "annualSales",
            label: false,
            displayName:"Annual Sales",
            value: "",
            type: inputTypes.number,
            columns: Columns.col6,
            inputClass: "",
            validation: {
                validationType: inputTypes.number,
                valid: null,
                required: false,
                lengthRequired: false,
                validationMessage: "",
            },
        },
        {
            name: "supplier",
            displayName: "Supplier",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "veteranOwned",
            displayName: "Veteran Owned",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "minorityOwned",
            displayName: "Minority Owned",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "womanOwned",
            displayName: "Woman Owned",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "buyAmerica",
            displayName: "Buy America Company",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "byAmerica",
            displayName: "By America",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "isoCertified",
            displayName: "ISO Certified",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "greenCertified",
            displayName: "Green Certified",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "establishedProduct",
            displayName: "Established Product",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false, 
        },
        {
            name: "portfolio",
            displayName: "Portfolio",
            type: inputTypes.checkbox,
            label: false,
            inline: false,
            inputClass: "",
            labelClass: "",
            columns: Columns.col12,
            value: false,
        },
        {
            name: "organizationSignupSubmit",
            displayName: "Submit",
            disabled: false,
            label: false,
            value: "",
            type: inputTypes.button,
            submitType: "organizationSignup",        
            variant: Variant.primary,
            wrapperClass: "",
            inputClass: "",
            columns: Columns.col6,
        },
    ],
    getValues: getValues,
    getValuesHelper: getValuesHelper,
}

function getValues(this: IForm):IOrganization {
    return {
        name:               getValuesHelper(this, "name"),
        phoneNumber:        getValuesHelper(this, "phoneNumber"), 
        website:            getValuesHelper(this, "website"),
        yearFounded:        getValuesHelper(this, "yearFounded"),
        numberOfEmployees:  getValuesHelper(this, "numberOfEmployees"),
        numberOfLocations:  getValuesHelper(this, "numberOfLocations"),
        annualSales:        getValuesHelper(this, "annualSales"),
        supplier:           getValuesHelper(this, "supplier"),
        buyAmerica:         getValuesHelper(this, "buyAmerica"),
        byAmerica:          getValuesHelper(this, "byAmerica"),
        minorityOwned:      getValuesHelper(this, "minorityOwned"),
        womanOwned:         getValuesHelper(this, "womanOwned"),
        veteranOwned:       getValuesHelper(this, "veteranOwned"),
        isoCertified:       getValuesHelper(this, "isoCertified"),
        greenCertified:     getValuesHelper(this, "greenCertified"),
        establishedProduct: getValuesHelper(this, "establishedProduct"),
        classifications: [
            getValuesHelper(this, "establishedProduct")
        ],
        address: {
            street:         getValuesHelper(this, "street"),
            city:           getValuesHelper(this, "city"),
            state_province: getValuesHelper(this, "state_province"),
            postalCode:     getValuesHelper(this, "postalCode"),
            country:        getValuesHelper(this, "country"),
        },
        adminUsers: [],
        users: []
    }
}

function getValuesHelper(form: IForm, name: string): any { 
    console.log(name);
    const input: any = form.inputs.find((input: IInput) => input.name === name);
    return input.value;
}