import { IInputProps, ICheckboxProps, IButtonProps, inputTypes } from "./FormInterfaces";

export const organizationSignupForm: Array< IInputProps | ICheckboxProps | IButtonProps>  = [
    {
        name: "name",
        label: false,
        displayName: "Company Name",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "street",
        label: false,
        displayName: "Street Number",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "state_province",
        label: false,
        displayName: "State or Province",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "city",
        label: false,
        displayName: "City",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "postalCode",
        label: false,
        displayName: "Postal Code",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string number",
            valid: null,
            required: true,
            lengthRequired: true,
            length: {min: 5, max: 10},
            validationMessage: "",
        }
    },
    {
        name: "country",
        label: false,
        displayName:"Country",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "mobileNumber",
        label: false,
        displayName:"Mobile Number",
        value: "",
        type: inputTypes.tel,
        pattern: "[0-9]*",
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string number",
            valid: null,
            required: false,
            lengthRequired: true,
            length: {min: 10, max: 10},
            validationMessage: "",
        }
    },
    {
        name: "officeNumber",
        label: false,
        displayName:"Office Number",
        value: "",
        type: inputTypes.tel,
        pattern: "[0-9]*",
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string number",
            valid: null,
            required: true,
            lengthRequired: true,
            length: {min: 10, max: 10},
            validationMessage: "",
        }
    },
    {
        name: "email",
        label: false,
        displayName:"Email",
        value: "",
        type: inputTypes.email,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: inputTypes.email,
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "classification",
        label: false,
        displayName:"Classification",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: false,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "yearFounded",
        label: false,
        displayName:"Year Founded",
        value: "",
        type: inputTypes.number,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "number",
            valid: null,
            required: true,
            lengthRequired: true,
            length: {min: 4, max: 4},
            validationMessage: "",
        }
    },
    {
        name: "website",
        label: false,
        displayName:"Website",
        value: "",
        type: inputTypes.text,
        columns:"col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            lengthRequired: false,
            required: false,
            validationMessage: "",
        }
    },
    {
        name: "qualityCertifications",
        label: false,
        displayName:"Quality Certifications",
        value: "",
        type: inputTypes.text,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: false,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "numberOfLocations",
        label: false,
        displayName:"Number Of Locations",
        value: "",
        type: inputTypes.number,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: inputTypes.number,
            valid: null,
            required: true,
            lengthRequired: true,
            length: {min: 1, max: 3},
            validationMessage: "",
        }
    },
    {
        name: "numberOfEmployees",
        label: false,
        displayName:"Employee Size",
        value: "",
        type: inputTypes.number,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: inputTypes.number,
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "annualSales",
        label: false,
        displayName:"Annual Sales",
        value: "",
        type: inputTypes.number,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: inputTypes.number,
            valid: null,
            required: false,
            lengthRequired: false,
            validationMessage: "",
        },
    },
    {
        name: "diversityAndOwnership",
        header: "Diversity and Ownership",
        withHeader: true,
        type: inputTypes.checkbox,
        list: true,
        inline: false,
        checkboxClass: "",
        labelClass: "",
        columns: "col-12",
        choices: [
            {name: "veteranOwned", displayName: "Veteran Owned", value: false,},
            {name: "minorityOwned", displayName: "Minority Owned", value: false,},
            {name: "womanOwned", displayName: "Woman Owned", value: false,},
            {name: "buyAmericaCompany", displayName: "Buy America Company", value: false,},
        ],
    },
    {
        name: "portfolio",
        header: "Portfolio",
        withHeader: true,
        type: inputTypes.checkbox,
        list: false,
        inline: false,
        checkboxClass: "",
        labelClass: "",
        columns: "col-12",
        choices: [{name: "portfolio", displayName: "Portfolio", value: false}],
    },
    {
        name: "organizationSignupSubmit",
        displayName: "Submit",
        disabled: false,
        type: inputTypes.button,
        submitType: "organizationSignup",        
        variant: "primary",
        wrapperClass: "",
        buttonClass: "",
        columns: "col-3",
    },
]