import { IInputProps, ICheckboxProps, IButtonProps, inputTypes } from "./FormInterfaces";

export const rfpForm: Array< IInputProps | ICheckboxProps | IButtonProps>  = [
    {
        name: "bidrequestName",
        label: false,
        displayName: "Bid Request Name",
        value: "",
        type: inputTypes.text,
        columns: "col-12",
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: true,
            length: {min: 1, max: 500},
            validationMessage: "",
        }
    },
    {
        name: "messageToBidders",
        label: false,
        displayName: "Message To Bidders",
        value: "",
        type: inputTypes.textarea,
        columns: "col-12",
        rows: 10,
        inputClass: "",
        validation: {
            validationType: "string",
            valid: null,
            required: true,
            lengthRequired: true,
            length: {min: 1, max: 3000},
            validationMessage: "",
        }
    },
    {
        name: "date",
        label: false,
        displayName: "Date",
        value: "",
        type: inputTypes.date,
        columns: "col-6",
        inputClass: "",
        validation: {
            validationType: "date",
            valid: null,
            required: true,
            lengthRequired: false,
            validationMessage: "",
        }
    },
    {
        name: "cbcRequirements",
        displayName: "CBC Requirements",
        type: inputTypes.checkbox,
        inline: false,
        checkboxClass: "",
        labelClass: "",
        columns: "col-12",
        value: false,
    },
    {
        name: "RfpSpecUpload",
        displayName: "File Upload",
        disabled: true,
        type: inputTypes.button,
        submitType: "api",
        variant: "secondary",
        wrapperClass: "",
        buttonClass: "",
        columns: "col-3",
    },
    {
        name: "RfpSubmit",
        displayName: "Submit",
        disabled: false,
        action: "handleSubmit",
        type: inputTypes.button,
        submitType: "api",
        variant: "primary",
        wrapperClass: "",
        buttonClass: "",
        columns: "col-3",
    },
]