export const FlameAndSmoke =  {
    name: "Flame And Smoke",
    displayName: "Flame And Smoke Requirements",
    param: "flame-smoke",
    subTitle: "Flame And Smoke",
    paragraphs: [
        {text: `All combustible components either separate or contained within an assembly must be specifically identified. For each individual item, data must be provided to document the following information:`},
        {text: `1) The material weight total within the component or system, and for each type of material used.`},
        {text: `2) Material specification sheets showing the total composition, mechanical, and all physical properties for each individual type of material used.`},
        {text: `3) All Material Specification Data Sheets (MSDS) for each individual material utilized in the assembly.`},
        {text: `4) Most current, independent laboratory testing reports with results for each material type, which should show the compliance to the following tests and test criteria:`},
        {text: `A) Boeing Specification Support Standard BSS-7239, meeting the following maximum gas release limits: `},
        {text: `- Carbon Monoxide (CO), 3500 ppm`},
        {text: `- Hydrogen Fluoride (HF), 200 ppm`},
        {text: `- Nitrogen Dioxide (NO2), 100 ppm`},
        {text: `- Hydrogen Chloride (HCL), 500 ppm `},
        {text: `- Hydrogen Cyanide (HCN), l50ppm`},
        {text: `- Sulfur Dioxide (SO2), 100 ppm`},
        {text: `B) ASTM E 162, with a flame spread index, Is ≤ 35`},
        {text: `C) ASTM E 662, with an optical smoke density, Ds (1.5 minutes) of ≤ 100 flaming and Non-flaming modes, \nDs (4.0 minutes) ≤ 200 Flaming and Non-Flaming modes.`},
        {text: `D) ASTM E 1354 Cone Calorimeter at a heat flux value of 50kW/m^2. See NFPA 130 "Annex D Rail Vehicle Fires", section D.2.1.1`},
        {text: `Note: Depending on specific systems, such as seat cushion, HVAC, floor covering, elastomers, upholstery etc.. May have different values it needs to meet. These values will be identified if necessary under their respective system under the system information once chosen button is press in the main screen.`},
        {text: `See NFPA 130 "Chapter 8 vehicles", section 8.4 "Fammability and Smoke Emission and table 8.4.1 for more information.`},
        {text: `See also:`},
        {text: `- CFR 238.103 "Fire safety"`},
        {text: `- Appendix B to part CFR 238" Test Methods and Performance Criteria for the Flammability and Smoke Emission Characteristics of Materials Used in Passenger Cars and Locomotive Cabs".`},
        {text: `- Cal TB 133 "California Technical Bulletin 133 and furniture fire safety"`},
    ]
}