export const FloorPanelStrengthAndTesting = {
    name: "Floor Panel Strength and Testing",
    displayName: "Floor Panel Strength and Testing Requirements",
    param: "floor-panel-strength-testing",
    subTitle: "Floor Panel Strength and Testing",
    paragraphs: [
        {text: `Floor panels can be of various compositions, including: honeycomb panels with aluminum skins, or plywood (better acustic properties) among others. However, it is a common industry standard for floor panels to be phenolic composite with a foam or balsa core.`},
        {text: `In any case, the floor panels must be design to withstand the following tests: `},
        {text: `The floor sample size used for testing shall be, unless specifically stated otherwise (such as stated in PRIIA, which requires a representative sample supported on beams spaced at the maximum spacing used on cars using production bonding and fastening techniques) , a 48X48 inch panel. This test panel is intended to be placed on supports 3 inches wide placed along each edge of the test panel. This will allow a 42 inch unsupported span upon which the tests can be performed. Alternate construction of the supports is allowed as long as the 42 inch unsupported span of the test panel is maintained.`},        
        {text: `Indentation Resistance -`},        
        {text: `load of 300 lbs is to be applied to the geometric center of the test panel over a 0.375 in. diameter area and inspected for the following to determine pass/fail of test:`},        
        {text: `1) Permanent deformation less than 0.010 inches.`},        
        {text: `2) No punctures or damage to fibers in the floor.`},        
        {text: `3) No visible or audible indications of delamination.`},        
        {text: `4) No fracture of the core after cross section.`},        
        {text: `Static Load Test-`},        
        {text: `A load of 170 lbs/ft2 (in some instances the load can be 200 lbs/ft2, as seen in PRIIA) is to be applied evenly over the entire floor sample and inspected for the following to determine pass/fail results of test:`},        
        {text: `1) No visible or audible indications of delamination.`},        
        {text: `2) Permanent deformation less than 0.010 inches.`},        
        {text: `3) Maximum surface deflection 0.168 in.`},        
        {text: `4) No separation of internal web (if applicable).`},        
        {text: `5) No failure of core material (if applicable). `},        
        {text: `Small Object Impact Test:`},        
        {text: `This test is to be performed using a spherical object weighing 16 pounds and with a diameter of 216 mm [8.5 in.]. The weight is to be dropped from a height of 60 inches and make impact on the geometrical center of the floor sample. Only one impact should occur therefore steps should be taken to prevent the weight from striking the sample a second time. After the impact the floor sample should be inspected for the following to determine pass/fail of test:`},        
        {text: `1) Permanent deformation of top surface less than 0.095 inches.`},        
        {text: `2) No puncture or damage to fibers in the floor.`},
        {text: `3) No separation of internal web.`},        
        {text: `4) Localized fracture of core permitted within a 6 inch radius.`},        
        {text: `5) Test to be performed without rubber floor covering.`},        
        {text: `Large Object Impact Test:`},
        {text: `This test is to be performed using a weight of 150 pounds dropped from a height of 12 inches onto the geometrical center of the test panel. The impact area of the weight onto the floor panel is to be a 24 in2 area. Only one impact should occur therefore steps should be taken to prevent the weight from striking the test panel a second time. After the impact the floor sample should be inspected for the following to determine pass/fail of test:`},        
        {text: `1) Permanent deformation of top surface less than 0.125 inches.`},
        {text: `2) No puncture or damage to fibers in the floor,`},
        {text: `3) No separation of internal web`},
        {text: `4) Localized failure permitted in an`},
        {text: `Small Area Static Load Test:`},
        {text: `A load of 300 pounds is to be applied over a 3 in2 area at the geometrical center of the test panel. After the load has been applied the sample should be inspected for the following to determine pass/fail of the test:`},
        {text: `1) No visible or audible indications of delamination.`},
        {text: `2) Permanent deformation less than 0.010 inches.`},
        {text: `3) No puncture or damage to fibers in floor.`},
        {text: `4) No separation of internal web.`},
        {text: `5) No fracture of the core after cross section`},
        {text: `Rolling Load Test:`},
        {text: `A 350 pound load is to be applied to the floor panel using a device that will allow a wheel to be rolled over the geometric center of the panel. The wheel is to be 3 inches in diameter and 1 inch wide and transfer the entire load to the point of contact between the floor panel and the wheel. The wheel should traverse the entire length of the panel twice. After the load has been applied the floor panel should be inspected for the following to determine pass/fail of test:`},
        {text: `1) No visible or audible indications of delamination of panel skin to core.`},
        {text: `2) Permanent deformation less than 0.010 inches.`},
        {text: `3) No punctures or damage to fibers in the floor.`},
        {text: `4) No separation of internal web.`},
        {text: `5) No fracture of the core after cross section.`},
        {text: `6) Test to be performed with and without rubber floor covering.`},
        {text: `Dynamic Load Cycle:`},
        {text: `A load between 200-210 pounds is to be applied to the geometric center of the floor. The load will be applied and removed for 1,000,000 cycles to complete the test. After all cycles are complete the floor panel shall be inspected for the following to determine pass/fail of test:`},
        {text: `1) No visible or audible indications of delamination of panel skin to core.`},
        {text: `2) Permanent deformation less than 0.010” of top surface.`},
        {text: `3) Less than 0.168” deflection after all cycles are completed.`},
        {text: `4) No separation of internal web.`},
        {text: `5) No fracture of the core after cross section.`},
        {text: `6) After successful completion of Dynamic Load Life Cycle test sample shall pass all criteria of Static Load Test.`},
        {text: `Threaded Inserts:`},
        {text: `Threaded inserts are required at various points in the floor to secure miscellaneous equipment and must be shown capable to hold such equipment without damage or slippage. Threaded inserts are to be installed using standard procedures in a sample sufficient in size to properly anchor the inserts in place. Once inserts are in place proper sized washers and bolts are to be fastened to each insert and using a torque wrench tightened to the appropriate torque. The inserts should be inspected for the following to determine pass/fail of the test:`},
        {text: `1) 8mm inserts withstand a torque load to 23 ft-lbs without rotation or damage.`},
        {text: `2) 10 mm inserts withstand a torque load to 45 ft-lbs without rotation or damage.`},
        {text: `3) Inserts withstand a tensile load to 500 lbs perpendicular to surface with no cracking or structural failure.`},
        {text: `Moisture Absorption And Mold Resistance:`},
        {text: `The floor panels shall be tested for moisture absorption and mold resistance with test protocols jointly agreed between Siemens and the supplier.`},
        {text: `For more information on derivatives of these tests, see  PRIIA (link below) section 18.12.7 and 4.4.4.9.`},
    ]
}